
Para compilar en w10 (en teoría):
gcc -I"C:RUTA\HACIA\PruebaPractica_1\include" -L"RUTA\HACIA\PruebaPractica_1\lib" agenda.c -ljson-c -o agenda 

Para ejecutar:
&& "C:RUTA\HACIA\PruebaPractica_1\Item1-C\ej_cuatro\"agenda

ó (ya en el directorio):

agenda.exe

Se pueden concatenar ambas (cmd):
gcc -I"C:RUTA\HACIA\PruebaPractica_1\include" -L"RUTA\HACIA\PruebaPractica_1\lib" agenda.c -ljson-c -o agenda && "C:RUTA\HACIA\PruebaPractica_1\Item1-C\ej_cuatro\"agenda