# Project: Databases
# Makefile created by Embarcadero Dev-C++ 6.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mantenedor.o
LINKOBJ  = mantenedor.o
LIBS     = -L"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/lib" -L"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Dev/mysql/mysql-8.0.24-winx64/lib" -lmysql
INCS     = -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/include" -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Dev/mysql/mysql-8.0.24-winx64/include" -I"C:/Dev/mysql/mysql-8.0.24-winx64/include/mysql"
CXXINCS  = -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/include" -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files/Embarcadero-Dev/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"C:/Dev/mysql/mysql-8.0.24-winx64/include" -I"C:/Dev/mysql/mysql-8.0.24-winx64/include/mysql"
BIN      = Databases.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = del /f /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN) 2>nul

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mantenedor.o: mantenedor.cpp
	$(CPP) -c mantenedor.cpp -o mantenedor.o $(CXXFLAGS)
